package HelloWorldApp;


/**
* HelloWorldApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* vendredi 24 octobre 2025 13 h 15 WET
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
